import bcrypt from 'bcryptjs'

const data = {
  users: [
    {
      name:'Jose',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name:'Prueba',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    }
  ],


  products: [
    {
      name: 'Outfit Floral Bohemio',
      category: 'Damas',
      image: '/images/p1_1.jpg',
      price: 25,
      countInStock: 0, 
      brand: 'Bohemio',
      rating: 5.0,
      numReviews: 25,
      description: 'Outfit de dos piezas espalda al aire floral Bohemio',
    },
    {
      name: 'Falda Drapeado Bohemio',
      category: 'Damas',
      image: '/images/p2_1.jpg',
      price: 15,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Falda drapeado Floral Bohemio',
    },
    {
      name: 'Falda con Volante Rígido Bohemio',
      category: 'Damas',
      image: '/images/p3_1.jpg',
      price: 20,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Falda volante rígido monocolor bohemio',
    },
    {
      name: 'Top a Rayas Bohemio',
      category: 'Damas',
      image: '/images/p4_1.jpg',
      price: 15,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 2.8,
      numReviews: 20,
      description: 'Outfit de dos piezas espalda al aire floral Bohemio',
    },
    {
      name: 'Braga/Mono Liso Bohemio',
      category: 'Damas',
      image: '/images/p5_1.jpg',
      price: 25,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Braga/Mono cut-out liso Bohemio',
    },
    {
      name: 'Braga Guigán Casual',
      category: 'Jovenes',
      image: '/images/c1_1.jpg',
      price: 10,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Lono para niña pequeña cremayera Guigán casual',
    },
    {
      name: 'Falda con Malla Ribete',
      category: 'Jovenes',
      image: '/images/c2_1.jpg',
      price: 15,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Falda con malla ribete en forma de lechuga dorada',
    },
    {
      name: 'Traje de Vestir con Rayas',
      category: 'Jovenes',
      image: '/images/c3_1.jpg',
      price: 20,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Traje de vestir camisa con lazo de rayas con short',
    },
    {
      name: 'Shot bajo',
      category: 'Jovenes',
      image: '/images/c4_1.jpg',
      price: 10,
      countInStock: 10, 
      brand: 'Bohemio',
      rating: 4.8,
      numReviews: 20,
      description: 'Short Bajo con Doblez',
    },
    {
      name: 'Set Cama Verde',
      category: 'Hogar',
      image: '/images/h1_1.jpg',
      price: 30,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Set de Cama Unicolor / 100% Poliester',
    },
    {
      name: 'Set Funda Edredón a Rayas',
      category: 'Hogar',
      image: '/images/h2_1.jpg',
      price: 20,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Ser funda edredón con patrón de rayas',
    },
    {
      name: 'Set Cama Negro',
      category: 'Hogar',
      image: '/images/h3_1.jpg',
      price: 25,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Set de Cama Unicolor / 100% Poliester',
    },
    {
      name: 'Set Sabana Turquesa',
      category: 'Hogar',
      image: '/images/h4_1.jpg',
      price: 25,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Set de Sabana Unicolor / 100% Poliester',
    },
    {
      name: 'Frasco Hermetico',
      category: 'Hogar',
      image: '/images/h5_1.jpg',
      price: 3,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Almacenamiento de comida protector',
    },
    {
      name: 'Almacenamiento de Cocina',
      category: 'Hogar',
      image: '/images/h6_1.jpg',
      price: 7,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Almacenamiento para cocina y alimentos',
    },
    {
      name: 'Cucharón Colador ',
      category: 'Hogar',
      image: '/images/h7_1.jpg',
      price: 3,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description:
        'Herramienta orada negra para vapor / Cucharón mejorado acanalado con filtro, colador',
    },
    {
      name: 'Set de 3 Cajas de Almacenaje',
      category: 'Hogar',
      image: '/images/h8_1.jpg',
      price: 15,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Set de 3 cajas de almacenaje para ropa interior',
    },
    {
      name: 'Almacenamiento baño',
      category: 'Hogar',
      image: '/images/h9_1.jpg',
      price: 7,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Almacenamiento baño liso/ dispensador de crema dental',
    },
    {
      name: 'Toalla de Baño',
      category: 'Hogar',
      image: '/images/h10_1.jpg',
      price: 7.99,
      countInStock: 10, 
      brand: 'Varios',
      rating: 4.8,
      numReviews: 20,
      description: 'Toalla de Baño',
    },
  ],
};
export default data;