const data = {
  products: [
    {
      _id: "1",
      name: "Outfit Floral Bohemio",
      category: "Damas",
      image: "/images/p1_1.jpg",
      price: 25,
      brand: "Bohemio",
      rating: 5.0,
      numReviews: 25,
      description: "Outfit de dos piezas espalda al aire floral Bohemio",
    },
    {
      _id: "2",
      name: "Falda Drapeado Bohemio",
      category: "Damas",
      image: "/images/p2_1.jpg",
      price: 15,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Falda drapeado Floral Bohemio",
    },
    {
      _id: "3",
      name: "Falda con Volante Rígido Bohemio",
      category: "Damas",
      image: "/images/p3_1.jpg",
      price: 20,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Falda volante rígido monocolor bohemio",
    },
    {
      _id: "4",
      name: "Top a Rayas Bohemio",
      category: "Damas",
      image: "/images/p4_1.jpg",
      price: 15,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Outfit de dos piezas espalda al aire floral Bohemio",
    },
    {
      _id: "5",
      name: "Braga/Mono Liso Bohemio",
      category: "Damas",
      image: "/images/p5_1.jpg",
      price: 25,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Braga/Mono cut-out liso Bohemio",
    },
    {
      _id: "6",
      name: "Braga Guigán Casual",
      category: "Jovenes",
      image: "/images/c1_1.jpg",
      price: 10,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Lono para niña pequeña cremayera Guigán casual",
    },
    {
      _id: "7",
      name: "Falda con Malla Ribete",
      category: "Jovenes",
      image: "/images/c2_1.jpg",
      price: 15,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Falda con malla ribete en forma de lechuga dorada",
    },
    {
      _id: "8",
      name: "Traje de Vestir con Rayas",
      category: "Jovenes",
      image: "/images/c3_1.jpg",
      price: 20,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Traje de vestir camisa con lazo de rayas con short",
    },
    {
      _id: "9",
      name: "Shot bajo",
      category: "Jovenes",
      image: "/images/c4_1.jpg",
      price: 10,
      brand: "Bohemio",
      rating: 4.8,
      numReviews: 20,
      description: "Short Bajo con Doblez",
    },
    {
      _id: "10",
      name: "Set Cama Verde",
      category: "Hogar",
      image: "/images/h1_1.jpg",
      price: 30,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Set de Cama Unicolor / 100% Poliester",
    },
    {
      _id: "11",
      name: "Set Funda Edredón a Rayas",
      category: "Hogar",
      image: "/images/h2_1.jpg",
      price: 20,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Ser funda edredón con patrón de rayas",
    },
    {
      _id: "12",
      name: "Set Cama Negro",
      category: "Hogar",
      image: "/images/h3_1.jpg",
      price: 25,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Set de Cama Unicolor / 100% Poliester",
    },
    {
      _id: "13",
      name: "Set Sabana Turquesa",
      category: "Hogar",
      image: "/images/h4_1.jpg",
      price: 25,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Set de Sabana Unicolor / 100% Poliester",
    },
    {
      _id: "14",
      name: "Frasco Hermetico",
      category: "Hogar",
      image: "/images/h5_1.jpg",
      price: 3,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Almacenamiento de comida protector",
    },
    {
      _id: "15",
      name: "Almacenamiento de Cocina/Despensa",
      category: "Hogar",
      image: "/images/h6_1.jpg",
      price: 7,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Almacenamiento para cocina y alimentos",
    },
    {
      _id: "16",
      name: "Cucharón Colador ",
      category: "Hogar",
      image: "/images/h7_1.jpg",
      price: 3,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description:
        "Herramienta orada negra para vapor / Cucharón mejorado acanalado con filtro, colador",
    },
    {
      _id: "17",
      name: "Set de 3 Cajas de Almacenaje",
      category: "Hogar",
      image: "/images/h8_1.jpg",
      price: 15,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Set de 3 cajas de almacenaje para ropa interior",
    },
    {
      _id: "18",
      name: "Almacenamiento baño liso/cremadental",
      category: "Hogar",
      image: "/images/h9_1.jpg",
      price: 7,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Almacenamiento baño liso/ dispensador de crema dental",
    },
    {
      _id: "19",
      name: "Toalla de Baño",
      category: "Hogar",
      image: "/images/h10_1.jpg",
      price: 7.99,
      brand: "Varios",
      rating: 4.8,
      numReviews: 20,
      description: "Toalla de Baño",
    },
  ],
};
export default data;