const data = {
    products:[
        {
            _id:'1',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:0.5,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
        {
            _id:'2',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:2.6,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
        {
            _id:'3',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:4.8,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
        {
            _id:'4',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:3.5,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
        {
            _id:'5',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:5.0,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
        {
            _id:'6',
            name:'Outfit floral Bohemio',
            category:'Shirts',
            image:'./images/p1_1.jpg',
            price: 240,
            brand:'García Dos Ramos',
            rating:4.5,
            description:'Outfit de dos piezas espalda al aire floral Bohemio',
        },
    ]
}
export default data;